### ISSUE TITLE
vagrant up --provider=xenserver error

### ISSUE THREAD

**Issue by dtatay** [jonludlam/vagrant-xenserver#12]
Hi; 

after vagrant up --provider=xenserver i have recieved this error and the VM on my xenserver is not booting..
im using Vagrant 1.7.1
i dont know how to continue so i contact you!
Could you please give me some suggestions?

==> default: Waiting for machine to boot. This may take a few minutes...
/root/.vagrant.d/gems/gems/vagrant-xenserver-0.0.9/lib/vagrant-xenserver/action/read_ssh_info.rb:40:in `read_ssh_info': undefined method `find' for nil:NilClass (NoMethodError)
        from /root/.vagrant.d/gems/gems/vagrant-xenserver-0.0.9/lib/vagrant-xenserver/action/read_ssh_info.rb:15:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/gems/vagrant-xenserver-0.0.9/lib/vagrant-xenserver/action/connect_xs.rb:28:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:212:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:189:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:485:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `action'
        from /root/.vagrant.d/gems/gems/vagrant-xenserver-0.0.9/lib/vagrant-xenserver/provider.rb:17:in `ssh_info'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:405:in `ssh_info'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:46:in `block in wait_for_ready'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:42:in `wait_for_ready'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'

**Comment by jonludlam** [comment]
The dev snapshots are available from xenserver.org - See here for example: http://xenserver.org/component/content/article/11-product/142-download-pre-release.html

**Comment by jcalonsoh** [comment]
does pre release from dev its like xenserver 6.5 recent release ??

**Comment by jcalonsoh** [comment]
Does you get on your xenserver

The bootloader for this VM returned an err -- did the VM installation succeed? Bootlable disk has no valid filesystem

**Comment by jonludlam** [comment]
XenServer 6.5 should work, yes. The bootloader error implies that the VM doesn't have a valid grub configuration that pygrub can read. How did you make your box image? and have you tried using HVM mode rather than PV?
