### ISSUE TITLE
Unable to connect to started VM

### ISSUE THREAD

**Issue by coffeepac** [jonludlam/vagrant-xenserver#16]
I am trying to start a Centos 6.4 VM on Xenserver 6.5 using this plugin.  I based my xen vagrant box off of mizzy/centos-6.4.  I'm getting the following output when running vagrant up:

> vagrant up --provider=xenserver
> Bringing machine 'default' up with 'xenserver' provider...
> 1+0 records in
> 1+0 records out
> 1048576 bytes (1.0 MB) copied, 0.00183077 s, 573 MB/s
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 169.254.0.2:22
>     default: SSH username: vagrant
>     default: SSH auth method: private key
> root@10.17.1.180's password: 
>     default: Warning: Connection timeout. Retrying...
> root@10.17.1.180's password: 
>     default: Warning: Remote connection disconnect. Retrying...
> root@10.17.1.180's password: 
> ==> default: Waiting for cleanup before exiting...
> root@10.17.1.180's password: Vagrant exited after cleanup due to external interrupt.

The command was in an infinite loop asking me for a password so I hit ctrl-C to exit.  The VM is partially coming up, I can access it through the console in XenCenter with vagrant/vagrant.  But it doesn't have an eth0, only loopback and I have been unable to figure out how to add eth0 via XenCenter tools.

The original vagrant box (mizzy/centos-6.4) works in virtual box and the qemu img conversion was successful.

Any ideas on what I can try debugging next or if there is a particular part of the plugin I should be poking around in to get some more info on what's going?

thanks

**Comment by jonludlam** [comment]
You need to do an ssh key swap with dom0. Something like:

    ssh-copy-id root@xenserver

**Comment by jonludlam** [comment]
I've updated the Readme to add these instructions. Thanks!
