### ISSUE TITLE
Support for windows OS

### ISSUE THREAD

**Issue by christopherRiddersater** [jonludlam/vagrant-xenserver#25]
Would it be possible to add support for Windows OS as well?

I don't really have the coding skills necessary but it looks like the vm is created using the "Other install media" Xenserver template and I don't think windows can boot using this template.

From the file create_vm.rb:
oim = env[:xc].call("VM.get_by_name_label",env[:session],"Other install media")['Value'][0]

Perhaps it would be possible to add a provisioner variable like template_name so that another template may be used instead?

Best regards,
Christopher

**Comment by jroweboy** [comment]
Hello Christopher! I'm just a user of this application, and I am working with Windows OS guests that I built from the virtual machines provided by modern.ie But I'm pretty sure that I'm not experiencing any issues related to the using Other Install Media. I can't say for sure yet, since I'm experiencing other issues that seem to unrelated, but I can create a patch for this and submit it as a PR if this is something that would be useful.

**Comment by christopherRiddersater** [comment]
Hi,

Many thanks for your response! :)
What I have seen so far is that the vm will not boot at all when I use the "Other install media" but if I detach the disk and attach it to a vm that was create using a Xenserver windows template it works fine.
My images is a Windows server 2012 R2 image built with Packer.

The error occurs just as I turn on the vm so it might perhaps be a boot loader thing or something like that but I realize that I owe it to you to do some proper research here since it seems to be working for you when you use the modern.ie machines. 

I will do some more research over the weekend and get back to you.
Would it be possible for you to share your vagrantfile for a working windows box with me?

Meanwhile, many thanks for opening up the dialog. :)

**Comment by christopherRiddersater** [comment]
Hi,

I have done some more research now and it turns out that I did too much copy paste and
I missed to change the pv property to false so it all works fine now. :)

It may be a good idea to provide the possibility to set the template anyway but it's not a high priority task.

Many thanks for your help and feedback! :)
